### ISSUE TITLE
modelsim/questa integration finds wrong vsim executable

### ISSUE THREAD

**Issue by bogdan-aldec** [Xilinx/XilinxTclStore#434]
modelsim/questa Tcl Store implementation looks for vsim executable through PATH entries. Problem is that executable with such name exists not only in modelsim/questa installations, which causes errors during simulation and forces customers to order PATH elements in specific way. It would be good to add additional condition to make sure that particular vsim is from modelsim/questa, for example if ( vsim.exe && modelsim.exe ) { this is good vsim }.

**Comment by rajklair** [comment]
Thanks for the suggestion, but it is expected that user needs to set the PATH correctly for the target simulator. Vivado GUI provides a way to set these paths simulator wise from tools->options which ensures correct vsim executable being referred from the flow. We will try to experiment with the condition as you suggested.
