### ISSUE TITLE
Sort type for each column

### ISSUE THREAD

**Issue by hseeger** [Xilinx/XilinxTclStore#459]
It would be nice to define a sort type for each sort column separately.
Actually, it's only possible to define one sort type for all columns to be sorted. But what if one column contains floating point number and another one contains text?

I think the necessary changes should be small.

**Comment by xlnxalecw** [comment]
Hi hseeger,
Can you specify which app and which proc you are referring to?
Thanks!

**Comment by hseeger** [comment]
Oh, I'm sorry.
I was referring to the procedure prettyTable of designutils.

**Comment by dpefour** [comment]
Hello,

Thank you for your feedback and suggestion. There is no short term plan for enhancing the table reporting package, we will keep your suggestion in mind for the future.

Best regards,
David

**Comment by dpefour** [comment]
prettyTable has been enhanced for 2015.4 and upward. You will need to refresh the catalog and get designutils version 1.26 or above.

The changes are:
- <prettyTable> sort can now accept sticky option -real/-integer/-dictionary that applies for the columns defined afterward.

For example:
<prettyTable> sort -real -0 -dictionary +1 -integer +2

Column 0 is expected to have real values, column 1 string values and column 2 integer values

**Comment by dpefour** [comment]
Let me know if you have any issue with 2015.4

**Comment by hseeger** [comment]
HI David,

thank you very much for the update!
It works fine.

Thanks again.
Best regards.
Harald
