### ISSUE TITLE
create_bd_cell with property

### ISSUE THREAD

**Issue by walkthetalk** [Xilinx/XilinxTclStore#584]
create_bd_cell is too simple, if we can create cell with property, it will be better.

**Comment by bulatkhusainov** [comment]
Could you explain what do you mean by "too simple" and "better" in this context? Are you referring to 'ip_prototype_build' command?

**Comment by walkthetalk** [comment]
we can't assign property with 'create_bd_cell',
what I want is "create_with_property", in other words, using one single command, we can get what we want, but not two seperate command, (first, create, and then, set property)

**Comment by dpefour** [comment]
Is this issue related to a Tcl Store app? If so, please, refer to https://github.com/Xilinx/XilinxTclStore/wiki/Support and provide the requested information (app name, app version, Vivado release, steps to reproduce, ...)

**Comment by dpefour** [comment]
Github issues are exclusively reserved for Xilinx Tcl Store's apps. You should probably looking at Xilinx forums (https://forums.xilinx.com/). I will close the issue. Thank you.
