### ISSUE TITLE
'set_property ip_repo_paths' can't expand variables

### ISSUE THREAD

**Issue by walkthetalk** [Xilinx/XilinxTclStore#585]
following command can't work:
set_property ip_repo_paths { $my_ip_dir/a $my_ip_dir/b } [current_project]

the workaround is:
set_property ip_repo_paths [list $my_ip_dir/a $my_ip_dir/b] [current_project]

**Comment by bulatkhusainov** [comment]
Could you provide a piece of tcl code that reveals the bug?

**Comment by walkthetalk** [comment]
after execute genproj.sh in bash, I got following error:

WARNING: [IP_Flow 19-2248] Failed to load user IP repository '/mnt/zynq/testtcl/$origin_dir/ip/cmos'; Can't find the specified path.
If this directory should no longer be in your list of user repositories, go to the IP Settings dialog and remove it.

[testtcl.tar.gz](https://github.com/Xilinx/XilinxTclStore/files/648207/testtcl.tar.gz)

**Comment by dpefour** [comment]
Is this issue related to a Tcl Store app? If so, please, refer to https://github.com/Xilinx/XilinxTclStore/wiki/Support and provide the requested information (app name, app version, Vivado release, steps to reproduce, ...)

**Comment by walkthetalk** [comment]
I don't know if it is suitable to file issue here, just tcl problem, if not, can I get the right place?

**Comment by dpefour** [comment]
Github issues are exclusively reserved for Xilinx Tcl Store's apps. You should probably looking at Xilinx forums (https://forums.xilinx.com/). I will close the issue. Thank you.
