### ISSUE TITLE
(ultrafast::report_reset_signals) terminated abnormally

### ISSUE THREAD

**Issue by RYSD-222** [Xilinx/XilinxTclStore#691]
Hello. I ran report_reset_signals on Vivado2019.1. The target device is xazu2eg-sfvc784-1Q-q.
When executed without any options, the execution was completed in one day.
Vivado terminated abnormally when executed with the -verbose option.
Vivado dropped suddenly, there is no log files.

It was confirmed that it ended normally in the example design.
I want a result for my design with verbose option.
It may depend on the design. I can't find the solutions. I want advice.

The PC environment is Windows10 64bit, Memory = 32GB.

**Comment by dpefour** [comment]
The long runtime is due to the large number of get_cells/all_fanin queries that the script has to make, probably from the large number of sequential elements in the design. The crash is because of the large data structures that the script generates in verbose mode. In an attempt to fix the crash, I have restricted the usage of -verbose with -file, so that information is saved on file as it is created. Could you try the attached script? You just need to source it after install ultrafast app. Does it solve the crash?
[report_reset_signals.zip](https://github.com/Xilinx/XilinxTclStore/files/3692697/report_reset_signals.zip)
[Timing PRs (2019.2).xlsx](https://github.com/Xilinx/XilinxTclStore/files/3692698/Timing.PRs.2019.2.xlsx)

**Comment by RYSD-222** [comment]
Thank you for your support.
I executed report_reset_signals with both -verbose and -file options after source your report_reset_signals.tcl.
Vivado dropped similarly. 
The output result of the file ended in the middle of 8. checking missing_clock, 9. and 10. are not displayed.

**Comment by dpefour** [comment]
If you run the following command, how many clock pins are reported that are not driven by a clock pin?
check_timing -exclude {constant_clock pulse_width_clock unconstrained_internal_endpoints no_input_delay no_output_delay multiple_clock generated_clocks loops partial_input_delay partial_output_delay latch_loops }

**Comment by RYSD-222** [comment]
I executed the command. It is the following result.


1. checking no_clock
--------------------
 There is 1 register/latch pin with no clock driven by root clock pin: SPI_0_sck_io (HIGH)

 There are 61 register/latch pins with no clock driven by root clock pin: vclk_0_0 (HIGH)

 There are 61 register/latch pins with no clock driven by root clock pin: vclk_1_0 (HIGH)

 There are 61 register/latch pins with no clock driven by root clock pin: vclk_2_0 (HIGH)

 There are 61 register/latch pins with no clock driven by root clock pin: vclk_3_0 (HIGH)

 There is 1 register/latch pin with no clock (HIGH)

**Comment by dpefour** [comment]
Could you provide the report_reset_signals summary when -verbose is not used. it should be something like:
There are <XXX> pins that are asynchronous (asynchronous)
There are <XXX> pins that are synchronous (synchronous)
There are <XXX> pins that are driven by primary ports (port_driven)
There are <XXX> pins that are tied to power (tied_power)
There are <XXX> cells that have a combinational driver for the <XXX> pin (combinational_driver)
There are <XXX> cells that have missing clock definition on the destination clock pin or sequential element driving the <XXX> pin (missing_clock)
There are <XXX> pins that are unconnected (unconnected)
There are <XXX> pins that are tied to ground (tied_ground)

Could you comment-out the following line inside report_reset_signals.tcl?
	if {$count(missingClock)} { puts $FH [$tables(missingClock) print] }
It should be around line 680. Does the script completes after the above line commented-out?

There are not many missing clocks, so I don't understand why the script would stop there. It could be that you have a large number of unconencted pins or pins tied to ground and stdout in not fully flushed when Vivado exit.

**Comment by RYSD-222** [comment]
Thank you for your support.
I tried to source both report_reset_signals.tcl and checklist.tcl, and execute report_reset_signals.
As a result, I got a "missing)" message.
Could you confirm it?

I did the following:
source report_reset_signals.tcl
source checklist.tcl
::tclapp::xilinx::ultrafast::report_reset_signals -verbose -file my_report.rpt -no_tied

**Comment by dpefour** [comment]
I fixed a typo. Could you try the new scripts?
[report_reset_signals.zip](https://github.com/Xilinx/XilinxTclStore/files/3727176/report_reset_signals.zip)
Note: I have updated to tied_power/tied_ground tables to reduce the size by reporting only the output pin driving the net.
Let me know how it goes.

**Comment by RYSD-222** [comment]
Thank you.
I executed it. Vivado is running now.
I understand that the meaning of the Note is to run report_reset_signals without -no_tied,
so first I'm running with only both -verbose and -file options.

**Comment by RYSD-222** [comment]
I executed both with -no_tied and without -no_tied.
Both logs were output after 12 hours. Thank you very much.
With -no_tied , "10. checking tied ground" shows the following.

10. checking tied_ground
------------------------
  No detailed table (-no_tied)

Without -no_tied, "10. checking tied ground" shows 60000 lines big table.

May I keep using this script?

**Comment by dpefour** [comment]
I am glad it worked. You can keep using the scripts. I will update the Tcl Store.
