### ISSUE TITLE
report_failfast fails if running a atched Vivado version

### ISSUE THREAD

**Issue by lukipedio** [Xilinx/XilinxTclStore#721]
report_failfast fails if running a patched Vivado version.

I am runnning the ::tclapp::xilinx::designutils::report_failfast in Vivado 2018.2_AR72992.

The script exits with error:
-E- expected version number but got "2018.2_0072992"

Luca

**Comment by dpefour** [comment]
The patch confuses the script to extract the Vivado release. Can you try the option --vivado-version to force the version to the script?
 ::tclapp::xilinx::designutils::report_failfast --vivado-version 2018.2 .........

**Comment by lukipedio** [comment]
Thanks.

I didn't check in the source code of the script.
This option is not documented.

I will try later since the patched Vivado version is on a Jenkins server that will run compilation later.

I will let you know.

**Comment by lukipedio** [comment]
I have made a fast test.
It works.
Thsnks!

**Comment by dpefour** [comment]
I am glad it works. That's right that --vivado-version is not documented since it was not meant to be mainstream. But using a patch is a case when it is a useful workaround.

**Comment by lukipedio** [comment]
I agree it should not be mainstream.

But customers with patches will complain about the time of the patch. But I can understand why.

Maybe it could be documented in an answer record.
